"""Export Module - HTML/PDF generation using markdown and weasyprint."""

import re
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

import markdown

try:
    from playwright.sync_api import sync_playwright
    HAS_PLAYWRIGHT = True
except ImportError:
    HAS_PLAYWRIGHT = False

from .variables import VariableProcessor

DEFAULT_STYLE = (
    "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', "
    "Roboto, sans-serif; line-height: 1.6; max-width: 800px; "
    "margin: 0 auto; padding: 2rem; }\n"
    "h1, h2, h3 { color: #333; border-bottom: 1px solid #eee; "
    "padding-bottom: 0.3em; }\n"
    "table { border-collapse: collapse; width: 100%; margin: 1rem 0; }\n"
    "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }\n"
    "th { background: #f5f5f5; }\n"
    "code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; "
    "font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace; }\n"
    "pre { background: #f4f4f4; padding: 1rem; overflow-x: auto; "
    "border-radius: 5px; }\n"
    "li { margin: 0.5rem 0; }\n"
    "blockquote { border-left: 4px solid #ddd; padding-left: 1rem; "
    "color: #777; margin: 1rem 0; }"
)


def convert_markdown_to_html(md_content: str, title: str = "Document", css: Optional[str] = None) -> str:
    """Convert Markdown to HTML with styling."""
    body_html = markdown.markdown(
        md_content,
        extensions=['extra', 'admonition', 'codehilite', 'toc']
    )

    style = css if css else DEFAULT_STYLE

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        {style}
    </style>
</head>
<body>
{body_html}
<hr>
<footer style="font-size: 0.8em; color: #888; text-align: center;">
    Generated by Scoper
</footer>
</body>
</html>"""


def export_to_html(
    input_file: str, output_file: Optional[str] = None, css_file: Optional[str] = None
) -> Path:
    """Export SOW to HTML."""
    input_path = Path(input_file)
    content = input_path.read_text()

    css = Path(css_file).read_text() if css_file and Path(css_file).exists() else None
    
    # Try to find style.css in the same directory as input_file if not provided
    if not css:
        local_css = input_path.parent / "style.css"
        if local_css.exists():
            css = local_css.read_text()

    title = input_path.stem.replace('-', ' ').title()
    html_content = convert_markdown_to_html(content, title, css)

    if output_file:
        output_path = Path(output_file)
    else:
        output_path = input_path.with_suffix('.html')

    output_path.write_text(html_content)
    return output_path


def export_to_pdf(input_file: str, output_file: Optional[str] = None, css_file: Optional[str] = None) -> Path:
    """Export SOW to PDF using Playwright Chromium."""
    if not HAS_PLAYWRIGHT:
        html_path = export_to_html(input_file, output_file.replace('.pdf', '.html') if output_file else None, css_file)
        logger.warning(f"Playwright not installed. Saved HTML instead: {html_path}")
        return html_path

    input_path = Path(input_file)
    content = input_path.read_text()
    
    css = Path(css_file).read_text() if css_file and Path(css_file).exists() else None
    if not css:
        local_css = input_path.parent / "style.css"
        if local_css.exists():
            css = local_css.read_text()

    # If the input is already HTML, don't wrap it again
    if input_path.suffix.lower() == '.html':
        html_content = content
    else:
        title = input_path.stem.replace('-', ' ').title()
        html_content = convert_markdown_to_html(content, title, css)

    if output_file:
        output_path = Path(output_file)
    else:
        output_path = input_path.with_suffix('.pdf')

    # Use Playwright
    temp_html = input_path.with_suffix('.temp.html')
    temp_html.write_text(html_content)
    
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(f"file://{temp_html.resolve()}", wait_until="networkidle")
            page.pdf(
                path=str(output_path),
                format="A4",
                print_background=True,
                display_header_footer=True,
                header_template="<div style='font-size: 7px; font-family: Inter, sans-serif; font-weight: 700; color: #64748b; text-align: right; width: 100%; margin: 0 10mm; padding-top: 4mm; border-top: 3px solid #0ea5e9; letter-spacing: 2px;'>STRICTLY CONFIDENTIAL &nbsp;//&nbsp; STRATEGIC SCOPE</div>",
                footer_template="<div style='font-size: 7px; font-family: Inter, sans-serif; font-weight: 600; color: #94a3b8; text-align: right; width: 100%; margin: 0 10mm; letter-spacing: 1px; padding-bottom: 4mm; border-top: 1px solid #e2e8f0; padding-top: 4mm;'>NEXUS ENGINE &nbsp;//&nbsp; PAGE <span class='pageNumber' style='color: #0f172a;'></span> OF <span class='totalPages'></span></div>",
                margin={"top": "18mm", "right": "0", "bottom": "18mm", "left": "0"}
            )
            browser.close()
            
            # Post-process: Compress PDF
            try:
                from pypdf import PdfReader, PdfWriter
                reader = PdfReader(str(output_path))
                writer = PdfWriter()
                for page in reader.pages:
                    writer.add_page(page)
                for page in writer.pages:
                    page.compress_content_streams()
                with open(str(output_path), "wb") as f:
                    writer.write(f)
            except Exception as comp_e:
                logger.warning(f"Failed to compress PDF: {comp_e}")

    except Exception as e:
        if "Executable doesn't exist" in str(e):
            logger.error("Playwright Chromium browser is missing. Please run: playwright install chromium")
        else:
            logger.error(f"PDF Generation failed: {e}")
        
        # Fallback to HTML
        html_dest = output_path.with_suffix('.html')
        temp_html.rename(html_dest)
        logger.warning(f"Saved HTML instead: {html_dest}")
        return html_dest
    finally:
        if temp_html.exists():
            temp_html.unlink()

    return output_path


def export_raw_html_to_pdf(html_content: str, output_file: str) -> Path:
    """Export raw HTML string to PDF using Playwright in-memory."""
    output_path = Path(output_file)
    html_dest = output_path.with_suffix('.html')
    html_dest.write_text(html_content, encoding='utf-8')
    
    if not HAS_PLAYWRIGHT:
        logger.warning(f"Playwright not installed. Saved HTML instead: {html_dest}")
        return html_dest

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(html_content, wait_until="load")
            page.pdf(
                path=str(output_path),
                format="A4",
                print_background=True,
                display_header_footer=True,
                header_template="<div style='font-size: 7px; font-family: Inter, sans-serif; font-weight: 700; color: #64748b; text-align: right; width: 100%; margin: 0 10mm; padding-top: 4mm; border-top: 3px solid #0ea5e9; letter-spacing: 2px;'>STRICTLY CONFIDENTIAL &nbsp;//&nbsp; STRATEGIC SCOPE</div>",
                footer_template="<div style='font-size: 7px; font-family: Inter, sans-serif; font-weight: 600; color: #94a3b8; text-align: right; width: 100%; margin: 0 10mm; letter-spacing: 1px; padding-bottom: 4mm; border-top: 1px solid #e2e8f0; padding-top: 4mm;'>NEXUS ENGINE &nbsp;//&nbsp; PAGE <span class='pageNumber' style='color: #0f172a;'></span> OF <span class='totalPages'></span></div>",
                margin={"top": "18mm", "right": "0", "bottom": "18mm", "left": "0"}
            )
            browser.close()
            
            # Post-process: Compress PDF
            try:
                from pypdf import PdfReader, PdfWriter
                reader = PdfReader(str(output_path))
                writer = PdfWriter()
                for page in reader.pages:
                    writer.add_page(page)
                for page in writer.pages:
                    page.compress_content_streams()
                with open(str(output_path), "wb") as f:
                    writer.write(f)
            except Exception as comp_e:
                logger.warning(f"Failed to compress PDF: {comp_e}")

    except Exception as e:
        if "Executable doesn't exist" in str(e):
            logger.error("Playwright Chromium browser is missing. Please run: playwright install chromium")
        else:
            logger.error(f"PDF Generation failed: {e}")
        
        logger.warning(f"Saved HTML instead: {html_dest}")
        return html_dest

    return output_path



def export_to_markdown(
    input_file: str, output_file: Optional[str] = None
) -> Path:
    """Export with processed variables to markdown."""
    input_path = Path(input_file)
    content = input_path.read_text()

    processor = VariableProcessor()
    processed = processor.process(content)

    output_path = Path(output_file) if output_file else input_path
    output_path.write_text(processed)

    return output_path


def export_to_text(input_file: str, output_file: Optional[str] = None) -> Path:
    """Export as plain text."""
    input_path = Path(input_file)
    content = input_path.read_text()

    text = re.sub(r'#+ ', '', content)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    text = re.sub(r'```.*?```', '', text, flags=re.DOTALL)
    text = re.sub(r'`(.+?)`', r'\1', text)
    text = re.sub(r'\|.*?\|', '', text)

    if output_file:
        output_path = Path(output_file)
    else:
        output_path = input_path.with_suffix('.txt')

    output_path.write_text(text)
    return output_path


def convert_format(
    input_file: str, output_format: str, output_file: Optional[str] = None, css_file: Optional[str] = None
) -> Path:
    """Convert between formats."""
    if output_format == "html":
        return export_to_html(input_file, output_file, css_file)
    elif output_format == "pdf":
        return export_to_pdf(input_file, output_file, css_file)
    elif output_format in ["md", "markdown"]:
        return export_to_markdown(input_file, output_file)
    elif output_format in ["txt", "text"]:
        return export_to_text(input_file, output_file)
    else:
        msg = f"Unknown format: {output_format}. Available: html, pdf, md, txt"
        raise ValueError(msg)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        fmt = sys.argv[2] if len(sys.argv) > 2 else "html"
        convert_format(sys.argv[1], fmt)
