"""SOW Templates Module - Supports built-in and user-defined templates."""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

BUILTIN_TEMPLATE_DIR = Path(__file__).parent / "templates"
USER_TEMPLATE_DIR = Path.home() / ".config" / "scoper" / "templates"


def list_available_templates() -> List[str]:
    """List all available SOW templates from all sources."""
    templates = ["default", "standard", "simple"]

    for dir_path in [USER_TEMPLATE_DIR, BUILTIN_TEMPLATE_DIR]:
        if dir_path.exists():
            for f in dir_path.glob("*"):
                if f.suffix in [".md", ".jinja2", ".txt", ".html"] and f.stem not in templates:
                    templates.append(f.stem)

    return templates


def get_template_path(template_name: str) -> Optional[Path]:
    """Get the file path for a template."""
    # Check User directory first
    if USER_TEMPLATE_DIR.exists():
        for ext in [".md", ".jinja2", ".txt", ".html"]:
            tp = USER_TEMPLATE_DIR / f"{template_name}{ext}"
            if tp.exists():
                return tp

    # Check BUILTIN_TEMPLATE_DIR
    if BUILTIN_TEMPLATE_DIR.exists():
        for ext in [".md", ".jinja2", ".txt", ".html"]:
            tp = BUILTIN_TEMPLATE_DIR / f"{template_name}{ext}"
            if tp.exists():
                return tp

    return None


def get_template(template_name: str) -> Optional[str]:
    """Get template content by name."""
    if template_name in ["default", "standard", "simple"]:
        return get_builtin_template(template_name)

    path = get_template_path(template_name)
    return path.read_text() if path else None


def get_template_schema(template_name: str) -> Dict[str, Any]:
    """Get variable schema for a template if it exists."""
    # Built-in schemas could be added here if needed
    
    path = get_template_path(template_name)
    if path:
        schema_path = path.with_suffix(".vars.yaml")
        if schema_path.exists():
            try:
                return yaml.safe_load(schema_path.read_text()) or {}
            except Exception:
                return {}
    return {}


def get_builtin_template(name: str) -> str:
    """Get built-in template content."""
    templates = {
        "default": """# Statement of Work: {{project_name}}

**Project:** {{project_name}}
**Date:** {{date}}
**Version:** {{version}}

---

## 1. Project Overview

{{description}}

## 2. Scope

### In Scope
- {{in_scope}}

### Out of Scope
- {{out_of_scope}}

## 3. Deliverables

- {{deliverable_1}}
- {{deliverable_2}}

## 4. Timeline

Start: {{start_date}} | End: {{end_date}}

## 5. Budget

${{budget}}

---

*Generated by Scoper*
""",
        "standard": """# Statement of Work: {{project_name}}

**Client:** {{client_name}}
**Project:** {{project_name}}
**Date:** {{date}}
**Version:** {{version}}
**Author:** {{author}}

---

## 1. Executive Summary

{{executive_summary}}

## 2. Project Overview

### 2.1 Background
{{project_background}}

### 2.2 Objectives
- {{objective_1}}
- {{objective_2}}
- {{objective_3}}

### 2.3 Success Criteria
{{success_criteria}}

## 3. Scope of Work

### 3.1 In Scope
- {{in_scope_1}}
- {{in_scope_2}}
- {{in_scope_3}}

### 3.2 Out of Scope
- {{out_of_scope_1}}
- {{out_of_scope_2}}

## 4. Deliverables

| # | Deliverable | Description | Due Date | Owner |
|---|------------|------------|---------|-------|
| 1 | {{deliverable_1}} | | | |
| 2 | {{deliverable_2}} | | | |
| 3 | {{deliverable_3}} | | | |

## 5. Timeline

| Phase | Activity | Start | End | Duration |
|-------|---------|-------|-----|---------|
| 1 | {{phase_1}} | | | |
| 2 | {{phase_2}} | | | |
| 3 | {{phase_3}} | | | |

## 6. Budget

**Total:** ${{total_budget}}

## 7. Assumptions

- {{assumption_1}}
- {{assumption_2}}

## 8. Acceptance Criteria

- {{acceptance_1}}
- {{acceptance_2}}

## 9. Sign-Off

| Role | Name | Signature | Date |
|------|------|----------|-----|
| Client | | | |
| Provider | | | |

---

*Generated by Scoper*
""",
        "simple": """# Statement of Work: {{project_name}}

**Project:** {{project_name}}
**Date:** {{date}}

---

## Overview
{{project_description}}

## Scope
**In:** {{in_scope}}
**Out:** {{out_of_scope}}

## Deliverables
- {{deliverable_1}}
- {{deliverable_2}}

## Timeline
- Start: {{start_date}}
- End: {{end_date}}

## Budget
${{budget}}

---
"""
    }

    return templates.get(name, templates["default"])


def get_template_info(template_name: str) -> dict:
    """Get template metadata including required variables."""
    content = get_template(template_name)
    if not content:
        return {}

    variables = re.findall(r'\{\{(\w+)\}\}', content)
    variables = list(set(variables))
    
    schema = get_template_schema(template_name)

    return {
        "name": template_name,
        "variables": variables,
        "variable_count": len(variables),
        "schema": schema
    }


def copy_template(source: str, dest: str) -> None:
    """Copy a template to a destination."""
    content = get_template(source)
    if not content:
        raise ValueError(f"Template '{source}' not found")

    Path(dest).write_text(content)


if __name__ == "__main__":
    print("Available templates:")
    for t in list_available_templates():
        print(f"  - {t}")
